name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - run: yarn install --frozen-lockfile
      name: Build

    - name: Archive pre-built bindings
      uses: actions/upload-artifact@v2
      with:
        name: binding
        path: binding/**
